#### INITIAL SETTINGS

# 1) PATHS
data_directory: ../data
raw_data: /raw
clean_data: /clean
predictions_data: /predictions
preprocessor_directory: ../data/transformer/
models_directory: ../models/

# 2) DATA
data_clean: clean.csv
data_train: train.csv
data_test: test.csv
target_name: SalePrice
numerical: ["LotFrontage","LotArea","OverallQual","OverallCond","YearBuilt","YearRemodAdd",
            "MasVnrArea","BsmtFinSF1","BsmtFinSF2","BsmtUnfSF","TotalBsmtSF","1stFlrSF",
            "2ndFlrSF","LowQualFinSF","GrLivArea","BsmtFullBath","BsmtHalfBath","FullBath",
            "HalfBath","BedroomAbvGr","KitchenAbvGr","TotRmsAbvGrd","Fireplaces","GarageYrBlt",
            "GarageCars","GarageArea","WoodDeckSF","OpenPorchSF","EnclosedPorch","3SsnPorch",
            "ScreenPorch","PoolArea","MiscVal","YrSold","MoSold"]
nominal: ["MSZoning","Street","Alley","LandContour","Utilities",
          "LotConfig","Neighborhood","Condition1","Condition2","BldgType",
          "HouseStyle","RoofStyle","RoofMatl","Exterior1st","Exterior2nd","MasVnrType",
          "Foundation","Heating","Electrical","GarageType","MiscFeature","SaleType","SaleCondition"]
to_drop: ["id","LotShape","LandSlope","ExterQual","BsmtFinType1","BsmtFinType2","HeatingQC",
           "CentralAir","KitchenQual","Functional","FireplaceQu","GarageFinish","GarageQual",
           "GarageCond","PavedDrive","PoolQC","Fence","BsmtQual","BsmtCond","ExterCond","MSSubClass"]

preprocessor_name: preprocessor.pkl

# 3) MODELS
best_model_parameters: best_model_params.pkl
gs_best_model_name: gs_bestmodel.pkl


# 4) RESULTS
predictions: predictions.csv

